config/routes.rb
Rails.application.routes.draw do
  root to: 'homepage#index'
  get 'user', to: 'homepage#user'
  resources :budgets
  resources :categories do
    collection do
      get 'fund_categories'
      get 'budget_categories'
    end
  end
  post 'create_link_token', to: 'plaid_credentials#create_link_token'
  post 'create_link_token_update/:access_token', to: 'plaid_credentials#create_link_token_update'
  post 'exchange_public_token/:public_token', to: 'plaid_credentials#exchange_public_token'
  get 'sync_transactions', to: 'plaid_credentials#sync_transactions'
  get 'get_balances', to: 'plaid_credentials#get_balances'
  resources :accounts
  resources :transactions
  resources :plaid_credentials
  devise_for :users,
    controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
    }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "plaid_credentials/index"
  get '/*path' => 'homepage#index'
  
end

app/models/budget.rb
class Budget < ApplicationRecord
    belongs_to :user
    has_many :transactions
    has_many :categories

    def update_categories
        categories = Category.where(category_type:'monthly').map(&:name).uniq
        self.update(start_date: Date.new(self.year.to_i, Date::MONTHNAMES.index(self.month), 1),
                     end_date: Date.new(self.year.to_i, Date::MONTHNAMES.index(self.month), -1))
        categories.map do |c| 
          b = Category.where(category_type: 'monthly').order("created_at DESC").find_by(name: c)
          b = b.dup
          b.update(budget_id: self.id, budget_month: self.month, current: b.budget_amt)
        end
        self.update(budget_amount: self&.categories&.map(&:budget_amt)&.sum, balance: self&.categories&.map(&:current)&.sum)
        self.update(rollover: self.balance)
    end

    def update_budget_amt
      self.update(current: self.budget_amount) if !self.categories.map{|c| c&.transactions}
    end

end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_action :set_budget, only: %i[ show edit update destroy ]

  # GET /budgets or /budgets.json
  def index
    @budgets = Budget.where(user_id: current_user.id).order(:created_at)
    render json: @budgets.to_json(:include => {:categories => {only: [:name, :current, :budget_amt]}})

  end

  # GET /budgets/1 or /budgets/1.json
  def show
    @budget.categories.each{|c| c.update_self}
    render :json => @budget.to_json(include: {categories: {only: [:id, :name, :current, :budget_amt], include: :transactions}})
  end

  # GET /budgets/new
  def new
    @budget = Budget.new
  end

  # GET /budgets/1/edit
  def edit
  end

  # POST /budgets or /budgets.json
  def create
    @budget = current_user.budgets.build(budget_params)

    if @budget.save
      @budget.update_categories
      render json: @budget, status: :created, location: budget_path(@budget)
    else
      render json: @budget.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /budgets/1 or /budgets/1.json
  def update
    if @budget.update(budget_params)
      @budget.update_budget_amt
      render json: @budget, location: budget_path(@budget)
    else
      render json: @budget.errors.messages, status: :unprocessable_entity
    end
  end

  # DELETE /budgets/1 or /budgets/1.json
  def destroy
    @budget.categories.each{|c| c.destroy}
    @budget.destroy

    render json: { message: 'Deleted!' }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_budget
      @budget = Budget.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def budget_params
      params.require(:budget).permit(:month, :year, :balance, :budget_amount, :start_date, :end_date, :rollover, :user_id)
    end
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/views/budgets/_budget.html.erb
<div id="<%= dom_id budget %>">
  <p>
    <strong>Month:</strong>
    <%= budget.month %>
  </p>
  <table>
    <tr>
      <th>Budget Item</th>
      <th>Budget Amount</th>
      <th>Budget Balance</th>
      <th>Status</th>
      <th>Budget Type</th>
    </tr>
    <% budget.categories.each do |c|%>
    <tr>
      <td><%= c.name %></td>
      <td><%= c.budget_amt %></td>
      <td><%= c.current %></td>
      <td><%= c.status ? c.status : 'None' %></td>
      <td><%= c.budget_type ? c.budget_type : 'None' %></td>
    </tr>
    <%end%>
  </table>

  <p>
    <strong>Balance:</strong>
    <%= budget.balance %>
  </p>

  <p>
    <strong>Budget amount:</strong>
    <%= budget.budget_amount %>
  </p>

  <p>
    <strong>Start date:</strong>
    <%= budget.start_date %>
  </p>

  <p>
    <strong>End date:</strong>
    <%= budget.end_date %>
  </p>

  <p>
    <strong>Rollover:</strong>
    <%= budget.rollover %>
  </p>

</div>

app/views/budgets/_form.html.erb
<%= form_with(model: budget) do |form| %>
  <% if budget.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(budget.errors.count, "error") %> prohibited this budget from being saved:</h2>

      <ul>
        <% budget.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :month, "Month in #{Date.today.year}", style: "display: block" %>
    <%= form.select :month, Date::MONTHNAMES[1..12] %>
  </div>

  <div>
    <%= form.hidden_field :year, value: Date.today.year%>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/budgets/edit.html.erb
<h1>Editing budget</h1>

<%= render "form", budget: @budget %>

<br>

<div>
  <%= link_to "Show this budget", @budget %> |
  <%= link_to "Back to budgets", budgets_path %>
</div>

app/views/budgets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Budgets</h1>

<div id="budgets">
  <% @budgets.each do |budget| %>
    <%= render budget %>
    <p>
      <%= link_to "Show this budget", budget %>
    </p>
  <% end %>
</div>

<%= link_to "New budget", new_budget_path %>

app/views/budgets/new.html.erb
<h1>New budget</h1>

<%= render "form", budget: @budget %>

<br>

<div>
  <%= link_to "Back to budgets", budgets_path %>
</div>

app/views/budgets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @budget %>

<div>
  <%= link_to "Edit this budget", edit_budget_path(@budget) %> |
  <%= link_to "Back to budgets", budgets_path %>

  <%= button_to "Destroy this budget", @budget, method: :delete %>
</div>