config/routes.rb
Rails.application.routes.draw do
  root to: 'homepage#index'
  get 'user', to: 'homepage#user'
  resources :budgets
  resources :categories do
    collection do
      get 'fund_categories'
      get 'budget_categories'
    end
  end
  post 'create_link_token', to: 'plaid_credentials#create_link_token'
  post 'create_link_token_update/:access_token', to: 'plaid_credentials#create_link_token_update'
  post 'exchange_public_token/:public_token', to: 'plaid_credentials#exchange_public_token'
  get 'sync_transactions', to: 'plaid_credentials#sync_transactions'
  get 'get_balances', to: 'plaid_credentials#get_balances'
  resources :accounts
  resources :transactions
  resources :plaid_credentials
  devise_for :users,
    controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
    }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "plaid_credentials/index"
  get '/*path' => 'homepage#index'
  
end

app/models/account.rb
class Account < ApplicationRecord
    belongs_to :user
    has_many :transactions
    belongs_to :plaid_credential, optional: true
    has_many :categories
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: %i[ show edit update destroy ]

  # GET /accounts or /accounts.json
  def index
    @accounts = Account.where(user_id: current_user.id).sort_by(&:subtype)
    render json: @accounts
  end

  # GET /accounts/1 or /accounts/1.json
  def show
    render json: @account
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts or /accounts.json
  def create
    @account = current_user.accounts.build(account_params)

    if @account.save
      render json: @account, status: :created, location: account_path(@account)
    else
      render json: @account.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /accounts/1 or /accounts/1.json
  def update
    if @account.update(account_params)
      render json: @account, location: account_path(@account)
    else
      render json: @account.errors, status: :unprocessable_entity
    end
  end

  # DELETE /accounts/1 or /accounts/1.json
  def destroy
    n = @account.id
    Category.where(account_id: n).each{|c| c.update(account_id: 1)}
    @account.destroy
    Transaction.where(account_id: n).each{|t| t.destroy}

    render json: {message: 'Deleted!'}
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
      @txns = Transaction.where(account_id: @account.account_id)
    end

    # Only allow a list of trusted parameters through.
    def account_params
      params.require(:account).permit(:account_id, :available, :current, :limit, :last_four, :name, :official_name, :account_type, :subtype, :user_id, :institution_name)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_account.html.erb
<div id="<%= dom_id account %>">
  <p>
    <strong>Account:</strong>
    <%= account.account_id %>
  </p>

  <p>
    <strong>Available:</strong>
    <%= account.available %>
  </p>

  <p>
    <strong>Current:</strong>
    <%= account.current %>
  </p>

  <p>
    <strong>Limit:</strong>
    <%= account.limit %>
  </p>

  <p>
    <strong>Last four:</strong>
    <%= account.last_four %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= account.name %>
  </p>

  <p>
    <strong>Official name:</strong>
    <%= account.official_name %>
  </p>

  <p>
    <strong>Type:</strong>
    <%= account.account_type %>
  </p>

  <p>
    <strong>Subtype:</strong>
    <%= account.subtype %>
  </p>

</div>

app/views/accounts/_form.html.erb
<%= form_with(model: account) do |form| %>
  <% if account.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
        <% account.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.hidden_field :account_id, :value => Account.all.size.to_s %>
  </div>

  <div>
    <%= form.label :available, 'Amount in account', style: "display: block" %>
    <%= form.text_field :available %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.hidden_field :account_type, :value => 'depository' %>
  </div>

  <div>
    <%= form.hidden_field :subtype, :value => 'cash' %>
  </div>

  <div>
    <%= form.hidden_field :user_id, :value => current_user.id %>
  </div>

  <div>
    <%= form.hidden_field :institution_name, :value => 'Cash' %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render "form", account: @account %>

<br>

<div>
  <%= link_to "Show this account", @account %> |
  <%= link_to "Back to accounts", accounts_path %>
</div>

app/views/accounts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Accounts</h1>

<%= link_to "New cash account", new_account_path %>

<%= link_to 'Home', root_path%>

<button id='acctButton'> Get Accounts </button>

<script src="https://cdn.plaid.com/link/v2/stable/link-initialize.js"></script>
<script>
async function get_accounts(){
    const things = await fetch('/get_balances', {
        headers: {
            "content-type": "application/json"
        },
        method: "get"
    })
    const response = await things.json()
    console.log("response:", response)
} 

document.getElementById('acctButton').onclick = function() {
    get_accounts()
};
</script>
<div id="accounts">
  <table>
    <tr>
      <th>Name</th>
      <th>Available to spend</th>
      <th>Account Number</th>
      <th>Type</th>
      <th>Institution</th>
    </tr>
    <% @accounts.each do |account| %>
    <tr>
      <td><%= link_to "#{account.name}", account %></td>
      <td><%= account.available %></td>
      <td><%= account.last_four %></td>
      <td><%= account.subtype %></td>
      <td><%= account.institution_name %></td>
    </tr>
    <%end%>
  </table>
</div>

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render "form", account: @account %>

<br>

<div>
  <%= link_to "Back to accounts", accounts_path %>
</div>

app/views/accounts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @account %>

<div>
  <%= link_to "Edit this account", edit_account_path(@account) %> |
  <%= link_to "Back to accounts", accounts_path %>

  <%= button_to "Destroy this account", @account, method: :delete %>
</div>